# Generated by Django 3.1.7 on 2021-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='latitude',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='longitude',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
